# Generated by Django 3.0.8 on 2021-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatroom', '0004_auto_20210716_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
