# Generated by Django 3.0.8 on 2021-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatroom', '0005_auto_20210716_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
