# Generated by Django 3.0.8 on 2021-07-16 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chatroom', '0006_auto_20210716_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
