# Generated by Django 3.0.8 on 2021-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatroom', '0007_auto_20210716_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
